import Head from 'next/head'
import {ParallaxBanner, ParallaxBannerLayer} from "react-scroll-parallax";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <section className="flex flex-col items-center justify-center h-[1500px] flex-col">
                <div className=" w-[50vw]  flex-col gap-4 flex items-center  justify-center m-1">
                    <ParallaxBanner
                        layers={[
                            {
                                image: 'https://s3.ecompletocarros.dev/images/lojas/301/veiculos/111861/veiculoInfoVeiculoImagesMobile/vehicle_image_1660773652_d41d8cd98f00b204e9800998ecf8427e.jpeg',
                                speed: 10
                            },
                            {
                                speed: -10,
                                children: (
                                    <div className="absolute inset-0 flex items-center justify-center">
                                        <h1 className="py-8 text-8xl text-black w-full text-center font-thin bg-highlight-black">Hello
                                            World!</h1>
                                    </div>
                                ),
                            },
                            // {
                            //     image: 'https://s3.ecompletocarros.dev/images/lojas/301/veiculos/133507/veiculoInfoVeiculoImagesMobile/vehicle_image_1676637277_d41d8cd98f00b204e9800998ecf8427e.jpeg',
                            //     speed: -10
                            // },{
                            //     image: 'https://s3.ecompletocarros.dev/images/lojas/301/veiculos/135297/veiculoInfoVeiculoImagesMobile/vehicle_image_1677275187_d41d8cd98f00b204e9800998ecf8427e.jpeg',
                            //     speed: 10
                            // },
                        ]}
                        className="aspect-[2/1] rounded-2xl"

                    >
                    </ParallaxBanner>
                    <ParallaxBanner
                        layers={[
                            {
                                image: 'https://s3.ecompletocarros.dev/images/lojas/301/veiculos/135297/veiculoInfoVeiculoImagesMobile/vehicle_image_1677275187_d41d8cd98f00b204e9800998ecf8427e.jpeg',
                                speed: 10
                            },
                            {
                                speed: -10,
                                children: (
                                    <div className="absolute inset-0 flex items-center justify-center">
                                        <h1 className="py-8 text-8xl text-black w-full text-center font-thin bg-highlight-black">Hello
                                            World!</h1>
                                    </div>
                                ),
                            },
                        ]}
                        className="aspect-[2/1] rounded-2xl"

                    >
                    </ParallaxBanner>
                    <ParallaxBanner
                        layers={[
                            {
                                image: 'https://s3.ecompletocarros.dev/images/lojas/301/veiculos/133507/veiculoInfoVeiculoImagesMobile/vehicle_image_1676637277_d41d8cd98f00b204e9800998ecf8427e.jpeg',
                                speed: -10
                            },
                            {
                                speed: -10,
                                children: (
                                    <div className="absolute inset-0 flex items-center justify-center">
                                        <h1 className="py-8 text-8xl text-black w-full text-center font-thin bg-highlight-black">Hello
                                            World!</h1>
                                    </div>
                                ),
                            },

                        ]}
                        className="aspect-[2/1] rounded-2xl"

                    >
                    </ParallaxBanner>


                </div>

            </section>
        </>
    )
}
